name: IPTV Guncelleme Botu

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Yetkiyi doğrudan buraya bağlıyoruz

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Gerekli Kütüphaneleri Yukle
      run: pip install requests

    - name: Botu Calistir
      run: python bot.py

    - name: Degisiklikleri Github'a Kaydet
      env:
        HF_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add listem.m3u
        git commit -m "M3U Linki Guncellendi" || exit 0
        git push origin HEAD:main
