name: IPTV Guncelleme Botu

on:
  schedule:
    - cron: '15 * * * *'  # Her saatin 15. dakikasında çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Gerekli Kütüphaneleri Yukle
      run: pip install requests

    - name: Botu Calistir
      run: python bot.py

    - name: Degisiklikleri Github'a Kaydet
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add listem.m3u
        git commit -m "M3U Otomatik Güncellendi [skip ci]" || exit 0
        git pull --rebase origin main || true
        git push origin HEAD:main
